Add expense feature
Runtime-Terror-G3/expense-management-back-end pull request #8
Opened 2021-11-11 13:54 UTC by marianbalan

* Added ExpenseDto entity
* Added ExpenseViewModel entity
* Created POST endpoint for expenses

2021-11-11 14:35 UTC, georgianabaietilor commented on Service/src/main/java/service/Service.java
> +                optionalUser.get()
if you create a constructor in User entity 
  public User(int id){this.id=id;} 
you can change line 71 with 
  new User(expenseDto.getUserId()) 
and you won't need lines 61-65

2021-11-11 15:02 UTC, georgianabaietilor approved these changes

2021-11-11 15:23 UTC, leonard-pop reviewed
Do we really need 3 classes for Expense?

2021-11-11 18:43 UTC, oskarpicus commented on Service/src/main/java/service/Service.java
> +    }
Maybe this function should be moved to the Expense class in a similar form to the following:
`public static Expense from(ExpenseDto expense) {...}`

2021-11-11 19:03 UTC, oskarpicus requested changes

2021-11-11 19:03 UTC, oskarpicus commented on Rest/src/main/java/controller/ExpenseController.java
> +            expense = service.addExpense(expenseDto);
The code can be more concise, by directly returning the `service.addExpense(expenseDto);` (unless there is a compelling reason not to)

2021-11-11 19:37 UTC, marianbalan commented on Service/src/main/java/service/Service.java
> +    private Expense expenseDtoToExpense(ExpenseDto expenseDto) throws ServiceException {
Forgot to remove it

2021-11-12 07:19 UTC, oskarpicus approved these changes

2021-11-12 09:00 UTC, merged