Feature: added global exception handler
Runtime-Terror-G3/expense-management-back-end pull request #9
Opened 2021-11-11 15:50 UTC by georgianabaietilor

2021-11-11 19:21 UTC, oskarpicus requested changes

2021-11-11 19:21 UTC, oskarpicus commented on Rest/src/main/java/controller/GlobalExceptionHandler.java
> +        System.out.println("Am exception occurred and it was handled by the global exception handler");
Typo in the print message, should be `An exception...`

2021-11-11 19:21 UTC, oskarpicus commented on Rest/src/main/java/controller/GlobalExceptionHandler.java
> +    @ExceptionHandler(Exception.class)
Maybe we should specify to only catch the unchecked exceptions in this handler (`RuntimeException `and its descendents), since they are the only reason (from what I can think of, at least) that an INTERNAL SERVER ERROR is justified.

2021-11-11 19:45 UTC, oskarpicus approved these changes

2021-11-12 09:47 UTC, leonard-pop approved these changes

2021-11-12 18:09 UTC, merged